### PR TITLE
Push without force

### PR DESCRIPTION
**Pull request by MarcelMue**

### CODE REVIEW

**Comment by MarcelMue** [comment]
It's not pretty (at all) but seems to work for our usecase. WDYT?

**Comment by ubergesundheit** [comment]
btw can you also change [this line](https://github.com/giantswarm/subtree-util/pull/13/files#diff-72ee51f9043ab830b0776be3bc7a0b6fe4fd852c2081f658a392c75af6567e1dR201)

**Comment by MarcelMue** [comment]
I tested this here:
https://github.com/giantswarm/falco-app/pull/28
I simply set this branch here:
https://github.com/giantswarm/falco-charts/blob/2a6ec34cf0eda6fc535e341c4a3efa9e21946ae1/.github/workflows/sync-from-upstream.yaml#L18

**Review by ubergesundheit — CHANGES_REQUESTED** [review]
Good, can you also change this line? https://github.com/giantswarm/subtree-util/pull/13#issuecomment-884016545

**Comment by MarcelMue** [comment]
> btw can you also change [this line](https://github.com/giantswarm/subtree-util/pull/13/files#diff-72ee51f9043ab830b0776be3bc7a0b6fe4fd852c2081f658a392c75af6567e1dR201)

The link doesn't work for me :(

**Comment by ubergesundheit** [comment]
image

The text written to the PR comment contains still the word `force` 197/201

**Review by ubergesundheit — APPROVED** [review]
nice, please create a release after merge :)

**Comment by MarcelMue** [comment]
> nice, please create a release after merge :)

Should now all be done!

**Pull request merged**
